Feature 43 code server search
Metatavu/metaform-react pull request #44
Opened 2021-09-29 13:29 UTC by Chi-Chu319

resolves #43

2021-09-29 17:57 UTC, EVP1989 reviewed
Looks good

2021-09-30 09:39 UTC, anttileppa requested changes

2021-09-30 09:39 UTC, anttileppa commented on src/MetaformAutocompleteField.tsx
> +    return renderAutocomplete(field, formReadOnly, value);
Wouldn't it be easier to pass just readOnly property, that combines formReadOnly and field.readyonly properties into one readonly value?

2021-09-30 09:39 UTC, anttileppa commented on src/MetaformAutocompleteField.tsx
> +  renderAutocomplete: (field: MetaformField, formReadOnly: boolean, value: FieldValue) => JSX.Element;
```suggestion
  renderAutocomplete: (field: MetaformField, readOnly: boolean, value: FieldValue) => JSX.Element;
```

2021-09-30 09:39 UTC, anttileppa commented on src/MetaformAutocompleteField.tsx
> +  renderAutocomplete: (field: MetaformField, formReadOnly: boolean, value: FieldValue) => JSX.Element;
See comment on render method

2021-09-30 09:39 UTC, anttileppa commented on src/MetaformComponent.tsx
> +  renderAutocomplete: (field: MetaformField, formReadOnly: boolean, value: FieldValue) => JSX.Element;
```suggestion
  renderAutocomplete: (field: MetaformField, readOnly: boolean, value: FieldValue) => JSX.Element;
```

2021-09-30 09:39 UTC, anttileppa commented on src/MetaformFieldComponent.tsx
> +  renderAutocomplete: (field: MetaformField, formReadOnly: boolean, value: FieldValue) => JSX.Element;
```suggestion
  renderAutocomplete: (field: MetaformField, readOnly: boolean, value: FieldValue) => JSX.Element;
```

2021-09-30 09:39 UTC, anttileppa commented on src/MetaformSectionComponent.tsx
> +  renderAutocomplete: (field: MetaformField, formReadOnly: boolean, value: FieldValue) => JSX.Element;
```suggestion
  renderAutocomplete: (field: MetaformField, readOnly: boolean, value: FieldValue) => JSX.Element;
```

2021-10-07 11:02 UTC, merged